name: Automatic Mirroring

on: [ repository_dispatch, workflow_dispatch ]

jobs:
  mirror:
    # we can check github.repository_owner == 'apache'
    # if: github.repository == 'lampajr/mirroring-example'
    name: Sync the Kiegroup mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: lampajr/mirroring-example
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: enteee/git-sync-mirror:latest
          options: >
            --rm
            --env DEBUG=true
            --env SRC_REPO=${{ github.server_url }}/lampajr/mirroring-example.git
            --env DST_REPO=${{ github.server_url }}/lampajr/mirror-of-mirroring-example.git
            --env SRC_REPO_TOKEN=${{ secrets.GITHUB_TOKEN }}
            --env DST_REPO_TOKEN=${{ secrets.MY_PAT }}
            --env ONCE=true
          run: |
            ./bin/git-sync-mirror.sh