name: Automatic Mirroring

on: [push]

env:
  GIT_TRACE: "1"
  GIT_CURL_VERBOSE: "1"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: mirror
        run: |
          ls -la

          echo Step 1
          mkdir -p ~/.ssh
          echo "${{ secrets.PERSONAL_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo Step 2
          export GIT_SSH_COMMAND="ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -l git"
          echo Step 2.1
          git remote add mirror "https://github.com/lampajr/mirror-of-mirroring-example.git"
          echo Step 2.2
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"

          echo Step 3
          git remote remove mirror